version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file Udacity_DevOps_CI-CD2/.circleci/template.yml
              --stack-name-loustack1
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
